### ISSUE TITLE
Registry registrations are deleted when next time OS is started

### ISSUE THREAD

**Issue by ekfacile** [NyaMisty/PunchDataExchangeHost#1]
# Spec

Windows 10 Pro 22H2 (19045.3693) Japanese

# Symptom

After registering it in the registry, REG_SZ Debugger will be deleted the next time you start or restart the OS.

# Reproduce

1. Create `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DataExchangeHost.exe`
2. Create REG_SZ `Debugger` and path.
3. Perform drag and drop once in Windows Terminal and wait for a while. If you do not do this, the feature will not be enabled.
4. Actually drag and drop. Drag and drop is successful.
5. Restart the OS or shut down once and start the OS.
6. REG_SZ Debugger is missing from `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DataExchangeHost.exe`. Drag and drop will not be possible unless you register REG_SZ Debugger again.

**Comment by NyaMisty** [comment]
You probably have some antivirus killing that registry value.
